### ISSUE TITLE
请问Token上的主页是哪个应用的主页呀

### ISSUE THREAD

**Issue by 1514479778** [Exception0x0194/NAI-Generator-Flutter#4]

**Comment by Exception0x0194** [comment]
![48c701572c1addc891bd6d53d2061baf484640165](https://github.com/user-attachments/assets/e3cb78c3-b743-4a37-8f26-781f6e84317a)
![83efc03441e72d72da8d086ccf03bac2484640165](https://github.com/user-attachments/assets/d24d2000-c5d2-49db-aecd-680faa7a5870)
可以在 [novelai.net/stories](https://novelai.net/stories) 找到相关设置。
